language: node_js
sudo: false
node_js:
  - "14.15.5"
install:
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run test -- --coverage --collectCoverageFrom=src/**/*.ts --collectCoverageFrom=!src/server.ts
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
